# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'fsudrs.github.io'
baseurl: ''
title: 'Office of Digital Research and Scholarship'
description: 'Projects and Training Materials from the FSU Libraries Office of Digital Research and Scholarship'
permalink: pretty
logo: "https://www.lib.fsu.edu/sites/default/files/sites/default/files/upload/drs/dighum.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Tutorials
  url: /tutorials/
- title: Projects
  url: /projects/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  tutorials:
    title: Tutorials
    output: true
    description: "Tutorials for Digital Research Skills"
    feature_text: |
      Tutorials and Training
    feature_image: "https://drodz11.github.io/colors-of-ozu/objects/eos_ximageID_ybright-med.jpg"
  projects:
    title: Projects
    output: true 
    description: "DRS Projects"
    feature_text: |
        DRS Projects 
    feature_image: "https://drodz11.github.io/colors-of-ozu/objects/eos_ximageID_ybright-med.jpg"
